name: Expo Build

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  build:
    runs-on: ubuntu-latest  # macOSも選べますが、ここではUbuntuを選択

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Node.jsのバージョン

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Log in to EAS
        run: eas login
        env:
          EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}  # Expoのアクセストークンを環境変数で指定

      - name: Build Android
        run: eas build --platform android --non-interactive

      - name: Build iOS
        run: eas build --platform ios --non-interactive
